name: remote_database
description: "Paquete para el manejo de bases de datos remotas."
version: 2.0.0
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1
  very_good_analysis: ^10.0.0
