name: remote_database
description: "Paquete para el manejo de bases de datos remotas."
version: 1.0.6
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  build_runner: ^2.10.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mockito: ^5.5.1
  very_good_analysis: ^10.0.0
